### ISSUE TITLE
Query: can I use secure storage interface with c++ instead of raw poxis interface ?

### ISSUE THREAD

**Issue by overunix** [google/asylo#16]
Hi Dears,

I saw there is posix io interface for secure storage under "asylo/platform/storage/secure", where I need to manually set the encryption key with ioctl and mode with O_SECURE.

Can I use this feature via c++ fstream, i.e. how can I set the key and how can I refer this is an encrypted file ?

**Comment by KeithMoyer** [comment]
Currently, the only way to configure the secure storage system is through the O_SECURE + ioctl interface you discovered. However, we have plans to create additional ways for configuring secure storage that would not be tied to the file descriptor-based interfaces.

Theoretically, one could use the non-standard __gnu_cxx::stdio_filebuf interface to create a C++ stream on top of a file descriptor. A quick test, though, showed something doesn’t quite work when combining it with secure storage. This will need to be debugged.

BTW: In the future, these types of questions are probably best served by sending a message to the asylo-users mailing list.

- Keith (Asylo Team)

**Comment by overunix** [comment]
> Currently, the only way to configure the secure storage system is through the O_SECURE + ioctl interface you discovered. However, we have plans to create additional ways for configuring secure storage that would not be tied to the file descriptor-based interfaces.
> 
> Theoretically, one could use the non-standard __gnu_cxx::stdio_filebuf interface to create a C++ stream on top of a file descriptor. A quick test, though, showed something doesn’t quite work when combining it with secure storage. This will need to be debugged.
> 
> BTW: In the future, these types of questions are probably best served by sending a message to the asylo-users mailing list.
> 
> * Keith (Asylo Team)

Thanks Keith.
