### ISSUE TITLE
Query: thread local support when migrating existing codes to enclave with asylo

### ISSUE THREAD

**Issue by overunix** [google/asylo#17]
Dears,

I mean to use asylo to migrate existing C++ codes to enclave. Previously I cannot use ***thread local*** unless I set the TCSPolicy=0 (bound to untrusted thread). 
The existing codes have lots of thread creation/destroy operations. I this case, I am worrying setting tcspolicy=0 will run out of TCSs.

So am I suggested to set tcspolicy=0 and config enough TCSNums in this case ?

**Comment by hf** [comment]
Hi,

Enclave threads are not really like normal threads. It's a complex subject,
but basically setting a TCSPolicy of 1 is required. It doesn't make the
enclave less secure, it only means that an OS thread can return to the
enclave TCS without reentering it "from a clean slate," i.e. continue from
where the enclave yielded via the SGX mutex and condition variable
functions in the SDK. By reentering as a clean slate you'll be purging the
thread local state of the TCS. So be wary of that -- thread local state is
only really gone when you enter not when you exit the enclave.

TCS policy of 0 is fairly limiting and only useful if you don't plan on
using thread yielding. You should implement a smart thread pool strategy so
that your TCS count does not normally require values larger than the number
of logical processors. Each TCS costs 4KB, so they're not really cheap like
normal threads are.

**Comment by hf** [comment]
Sorry, reverse of what I said. 0 is for yielding, 1 is limiting.

**Comment by overunix** [comment]
@hf I agree with what you say about thread local behavior. I was worrying if tcs is not bounded,  different ecalls from the same OS thread might suffer from the purged thread local variables.
But now since asylo put all inside the enclave, it is not a problem since the same os thread wont perform mutiple ecalls into the enclave, as the thread function will be defined inside enclave in asylo. 
So I only need to care about tcsnum choose according to my app.
