### ISSUE TITLE
wget not avaible at asylo docker image

### ISSUE THREAD

**Issue by IonesioJunior** [google/asylo#18]
I was following the quick start guide to asylo applications and replicating the steps. I noticed that although in dockerfile the wget application is among the applications installed during the construction of the docker image, while running the image, the wget application is not installed. Is the docker image of this link updated?

Asylo Image : gcr.io/asylo-framework/asylo

**Comment by KeithMoyer** [comment]
Yes, that image is up-to-date. In the Dockerfile, wget is installed during the first temporary image, where the toolchain is built. It is not needed to use Asylo or build Asylo applications, so it is not installed in the final image. You can install it into a container or container image you create based this one, though.

**Comment by overunix** [comment]
the "wget xxx" instruction is mean to run at docker host machine and then mapped into docker

**Comment by IonesioJunior** [comment]
Ohh, thanks. I did not notice the temporary containers.
