### ISSUE TITLE
Errors when building primitives' example

### ISSUE THREAD

**Issue by anahitH** [google/asylo#19]
Hi.
I’m having problems when trying to build the example in platform/primitives/examples
I’ve built the docker image from Dockerfile and for building the example I’m following the steps in README.

First, when building hello_enclave with
          `bazel build :hello_enclave.so --config=asylo --define=ASYLO_SIM=1`
I get an error saying that config value asylo is not defined. 

Second, when building the hello_driver with
              `bazel build :hello_driver --define=ASYLO_SIM=1`
I get following compile error

![screenshot from 2019-03-07 00-48-18](https://user-images.githubusercontent.com/23015948/53922046-18066600-4073-11e9-936b-6d1cd78ee50c.png)

Any chance you could help to figure out what is wrong here?
Thanks!

**Comment by deeglaze** [comment]
The enclave.bazelrc file did not get updated, and we didn't properly rewrite the flags initialization command to use the namespace gflags uses (`google::`). We'll get this fixed soon. Meanwhile, you can add the namespace qualification to `ParseCommandLineFlags` and add the following lines to enclave.bazelrc to define --config=asylo:

```
build:asylo --crosstool_top=@com_google_asylo_sgx_backend//toolchain:crosstool
build:asylo --dynamic_mode=off
build:asylo --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
build:asylo --fission=no
build:asylo --custom_malloc=@com_google_asylo_sgx_backend//toolchain:malloc
build:asylo --define=grpc_no_ares=true
```
The untrusted_sim build target should get `linkopts = ["-ldl"],` added, and the `static constexpr char kTest[] = "Test";` in hello_test.cc should be moved outside the class into an anonymous namespace without `static`:

```
namespace {

constexpr char kTest[] = "Test";

}  // namespace
```

**Comment by anahitH** [comment]
thank you @deeglaze, this helped a lot
