### ISSUE TITLE
Provide more info on signing production SGX enclaves

### ISSUE THREAD

**Issue by ellipticasec** [google/asylo#2]
It'd be important to get some more practical information on how to sign production enclaves. I think one needs to request an enclave signing certificate from Intel.

**Comment by MWShan** [comment]
For the signing of production enclaves, you can follow the steps outlined here to request that your key be included in the whitelist: [https://software.intel.com/en-us/sgx/commercial-use-license-request ](url)

**Comment by KeithMoyer** [comment]
[Clickable link](https://software.intel.com/en-us/sgx/commercial-use-license-request)

**Comment by KeithMoyer** [comment]
It looks like @MWShan's (affiliated with Intel, not Asylo) reply answers your question.  If that's not the case, feel free to reopen this issue.
