### ISSUE TITLE
outdated description in manual installation description asylo/INSTALL.md

### ISSUE THREAD

**Issue by Ruide** [google/asylo#29]
Hi,

I find some descriptions might need update as following.

1.
"${ASYLO}"/sdk/asylo/distrib/sgx_x86_64/install-toolchain \
    --user \
    --prefix "${ASYLO}"/toolchains/sgx_x86_64

may need to be updated to 

"${ASYLO}"/sdk/asylo/distrib/toolchain/install-toolchain \
    --user \
    --prefix "${ASYLO}"/toolchains/sgx_x86_64

or else. Since the install-toolchain script is relocated.

2. 

The link address for distrib/README.md
https://github.com/google/asylo/blob/master/asylo/distrib/README.md
may want to change to
https://github.com/google/asylo/blob/master/asylo/distrib/toolchain/README.md

Thanks!

**Comment by KeithMoyer** [comment]
Good catch, Ruide! Fixed :-)
