### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [google/asylo#3]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [SetEnclaveConfig](https://github.com/google/asylo/blob/ac598c5266e36312d18fcdaa55efbc780af88975/asylo/platform/core/fake_trusted_global_state.cc#L50 "SetEnclaveConfig function")
- [SetEnclaveName](https://github.com/google/asylo/blob/ac598c5266e36312d18fcdaa55efbc780af88975/asylo/platform/core/trusted_global_state.cc#L29 "SetEnclaveName function")
- [EnclaveManager::Configure](https://github.com/google/asylo/blob/ac598c5266e36312d18fcdaa55efbc780af88975/asylo/platform/core/enclave_manager.cc#L201 "EnclaveManager::Configure function")

**Comment by udaysavagaonkar** [comment]
Thank you for pointing this out--we will address this in coming days.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/google/asylo/commit/8dd6e46cd156ff161d549921c48f050561c29bfd "Deletion of a few unnecessary checks").
