### ISSUE TITLE
Is asylo_redis example documentation broken?

### ISSUE THREAD

**Issue by shpark** [google/asylo#31]
Hi, I am trying out building asylo examples and found that `asylo_redis` documentation didn't work for me.

After trial and error and thanks to #28, I was able to make it work.

I am not sure whether I was wrong or the documentation itself was misleading, since I am totally new to Bazel build system ;)

I will file a PR. Could you please take a look?

FYI, I am building `asylo_redis` without Docker

**Comment by KeithMoyer** [comment]
Fixed by #32 

Thanks, again!
