### ISSUE TITLE
processor usage

### ISSUE THREAD

**Issue by mariomvk** [google/asylo#36]
Hi, 

I have problems with running grpc server inside SGX enclave with asylo.
Everything works but processor usage is strange.
Even when grpc server is running in idle 4 processor cores are used 100%

This can easily be reproduced by running grpc_server example from https://asylo.dev/asylo-examples.tar.gz

Could you please take a look?

![image](https://user-images.githubusercontent.com/3204790/60510515-d78cc100-9ccf-11e9-977d-2a42f8c5d231.png)

br,
Mario

**Comment by KeithMoyer** [comment]
Thanks, Mario.

This is an issue we've seen as well, and we've had discussions on how to best fix it. We'll try to get it addressed soon.

**Comment by sliverdragon37** [comment]
As of release 0.6.0, this is fixed.
