### ISSUE TITLE
SGX remote attestation

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#47]
Asylo has [definitions](https://github.com/google/asylo/blob/master/asylo/identity/descriptions.h) for several types of assertions:

 - `SetNullAssertionDescription`
 - `SetSgxLocalAssertionDescription`
 - `SetSgxRemoteAssertionDescription`

But it looks like only the first two are implemented in a form of gRPC credentials:
- [null_credentials_options.cc](https://github.com/google/asylo/blob/master/asylo/grpc/auth/null_credentials_options.cc)
- [sgx_local_credentials_options.cc](https://github.com/google/asylo/blob/master/asylo/grpc/auth/sgx_local_credentials_options.cc)

Does it mean that SGX remote attestation for gRPC is not yet implemented, or it is implemented but in different place/form?

**Comment by annasapek** [comment]
Keen observation! :) Yes, we're currently still working on getting SGX remote attestation working as a mode of gRPC authentication. Once it's available, you'll also find a sgx_remote_credentials_options.cc file.

See #39 for more details about the attestation scheme that we plan to support.
