### ISSUE TITLE
Util libraries are not public

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#49]
Should these functions:
https://github.com/google/asylo/blob/befb2efc1aa2bf6cf6f2ced869182ee3ce921817/asylo/identity/enclave_assertion_authority_configs.h#L63-L79

be visible in `visibility:public` (currently they are in `asylo:implementation`):
https://github.com/google/asylo/blob/befb2efc1aa2bf6cf6f2ced869182ee3ce921817/asylo/identity/BUILD#L122-L127

Since they may be used by asylo users during initialization?
```c++
std::vector<asylo::EnclaveAssertionAuthorityConfig> configs = {
    asylo::CreateNullAssertionAuthorityConfig(),
    asylo::CreateSgxLocalAssertionAuthorityConfig(),
};

asylo::Status status =
    asylo::InitializeEnclaveAssertionAuthorities(configs.begin(), configs.end());
```
Or enclave assertion authorities are already initialized by `asylo`?

**Comment by annasapek** [comment]
This library is intended to be `visibility:public` and we have commit in the pipeline to fix its visibility. It should get pushed out in the next week.

`asylo::InitializeEnclaveAssertionAuthorities()` only needs to be invoked manually outside an enclave. It is automatically invoked inside an enclave by [`TrustedApplication::InitializeInternal()`](https://github.com/google/asylo/blob/v0.4.1/asylo/platform/core/trusted_application.cc#L358-L360).

**Comment by ipetr0v** [comment]
@annasapek, so if we have a gRPC client and a gRPC server that hosts an enclave:
- Do we need to only run `asylo::InitializeEnclaveAssertionAuthorities()` on the client?
- Or we also need to run this function in the untrusted part of the server (outside the enclave)?

**Comment by annasapek** [comment]
If the gRPC endpoint (client or server) runs inside an enclave, you don't need to invoke `asylo::InitializeEnclaveAssertionAuthorities()` in either the trusted or untrusted portion.

If the gRPC endpoint runs outside an enclave, you _must_ call `asylo::InitializeEnclaveAssertionAuthorities()` manually.

**Comment by ipetr0v** [comment]
@annasapek should this library also be public ?
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/BUILD#L1166-L1190

Since it contains very convenient helper functions that should be used by asylo users:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/secs_attributes.h#L181-L182

https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/secs_attributes.h#L198-L200

**Comment by ipetr0v** [comment]
@annasapek should this library also be public ?
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/BUILD#L1166-L1190

Since it contains very convenient helper functions that should be used by asylo users:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/secs_attributes.h#L181-L182

https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/secs_attributes.h#L198-L200

**Comment by ipetr0v** [comment]
Also this library is also not public:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/util/BUILD#L55-L67

**Comment by annasapek** [comment]
No, we don't intend to make those public. The [`sgx_identity_util`](https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/sgx_identity_util.h) library should contain all the additional utility functions needed for gRPC authn and authz. Let me know if you think something is missing from there.

**Comment by ipetr0v** [comment]
Should `sha256_hash_util` be public, since it contains functions to create `Sha256HashProto` from strings? And these functions could be used to assign `MRSIGNER` values for the remote attestation.

**Comment by ipetr0v** [comment]
And also this library:
https://github.com/google/asylo/blob/befb2efc1aa2bf6cf6f2ced869182ee3ce921817/asylo/grpc/auth/BUILD#L61-L72

**Comment by annasapek** [comment]
You can depend on `asylo/grpc/auth:grpc++_security_enclave` to get the definition of `EnclaveCredentialsOptions`. The `enclave_credentials_options` target was created to isolate the code for testing.

**Comment by ipetr0v** [comment]
Thanks!
And on which library I can depend to get functions for `Sha256HashProto` creation?

**Comment by annasapek** [comment]
You can get that definition from `asylo/identity/util:sha256_hash_cc_proto`.

As a side-note, we are planning to reorg these directories so it is more clear which files are intended to be consumed by users of Asylo. I admit that it is a bit confusing right now.

**Comment by tiziano88** [comment]
The `asylo/identity/util:sha256_hash_cc_proto` rule exposes the proto file, but not the util class. We would probably reimplement something like `Sha256HashFromHexString` anyways, so could you consider making it public?

https://github.com/google/asylo/blob/e8bff4742f0a3314ba553897ba00bb6042835ba3/asylo/identity/util/sha256_hash_util.h#L32

**Comment by ipetr0v** [comment]
Another question:
It doesn't seem that `sgx_identity_util` util library contains primitives for creating `SgxIdentity`, except for:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/sgx_identity_util.h#L50-L51

And `SgxIdentity` is a required parameter for:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/sgx_identity_util.h#L64-L68

If I understand correctly, in order to create `SgxIdentity` manually, we need to set `code_identity->set_miscselect(...)` and `code_identity->mutable_attributes()`, using the following constants and functions:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/secs_miscselect.h#L37-L45

https://github.com/google/asylo/blob/5ab253e2db786a9cccbc397aac2338531d4aa119/asylo/identity/sgx/secs_attributes.h#L181-L182

But they are not public:
https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/identity/sgx/BUILD#L1166-L1178

**Comment by iKevinY** [comment]
@ipetr0v Thanks for pointing that out; this was indeed an oversight in the `sgx_identity_util` library. We'll work on exposing other methods that allow for creating non-self `SgxIdentity`s.

**Comment by iKevinY** [comment]
The latest Asylo release includes the addition of [`attributes_util`](https://github.com/google/asylo/blob/master/asylo/identity/platform/sgx/attributes_util.h) and [`miscselect_util`](https://github.com/google/asylo/blob/master/asylo/identity/platform/sgx/miscselect_util.h), which are public libraries that can be used to modify those `CodeIdentity` fields. The constants were moved into [`architecture_bits`](https://github.com/google/asylo/blob/master/asylo/identity/platform/sgx/architecture_bits.h) so that they can also be used.
