### ISSUE TITLE
SGX hardware mode

### ISSUE THREAD

**Issue by madhavsuresh** [google/asylo#5]
Hi, 

Is it possible to use Asylo in hardware mode? In particular, would anything in asylo break if the signed enclave shared object is linked against the hardware trts_library, and hardware service_library. Have there been complications in linking Asylo against the hardware libraries/running in hardware?

Btw, this project is really cool, thank you!

**Comment by matthewgingell** [comment]
Hi madhavsuresh,

That isn't a scenario we support yet, but we aren't aware of any technical complications other than tricky build config / linkage stuff. 

There are a few reasons we haven't released SGX hardware support: We haven’t done enough testing to be comfortable supporting hardware, and our support for some important features like remote attestation is still incomplete. For now, we want to be sure we’re positioning this initial release as a technology preview that allows people to start experimenting with our vision of backend-independent enclave development.

If your interest is academic or you're just curious about where Asylo is going, we definitely encourage you to experiment and let us know if you have any questions. 

Thanks,
Matt
