### ISSUE TITLE
asylo in GKE

### ISSUE THREAD

**Issue by fixerivan** [google/asylo#50]
any idea when asylo will be available to use in google kubernetes engine? would love that ... 

right now i am trying to use the GKE binary authorization, but that is quite limited - as remote attestation is what our use case needs 

thx

**Comment by KeithMoyer** [comment]
Unfortunately, I'll have to side-step this question. We can't comment on any kind of unannounced product plans or road maps. :-(

**Comment by fixerivan** [comment]
don't want to sound rude but there isn't too much activity on your blog, is this project still alive? or is the "new content" somewhere else? 

still hoping for that GKE support ... thx!

**Comment by KeithMoyer** [comment]
Indeed, we don't post often to the blog. However, a new release shouldn't be too far away. :-)
