### ISSUE TITLE
`asylo_package` bazel path builder breaks when external repository uses `asylo` in its name 

### ISSUE THREAD

**Issue by blaxill** [google/asylo#52]
The `asylo_package` helper function currently just checks if asylo is in the path and so breaks when external repository uses `asylo` in its name:

https://github.com/google/asylo/blob/088ea3490dd4579655bd5b65b0e31fe18de7f6dd/asylo/bazel/asylo_internal.bzl#L24-L27

For example compiling in an external repository: `bazel build //oak/server/asylo:xxxx` fails with `no such package 'asylo/bazel/application_wrapper'`.

**Comment by deeglaze** [comment]
This was a workaround for the --incompatible_remap_main_repo flag that still hasn't flipped in Bazel. I'll change it to .startswith("asylo") and hopefully that will be good enough until the flag is flipped. Thanks for the report!
