### ISSUE TITLE
Attribute 'deprecated' is ignored

### ISSUE THREAD

**Issue by ipetr0v** [google/asylo#57]
Compiling a new Asylo version (0.5.1) and get the following error:
```shell
external/com_google_asylo/asylo/crypto/aes_gcm_siv.h:76:1: error: attribute 'deprecated' is ignored, place it after "class" to apply attribute to type declaration [-Werror,-Wignored-attributes]
ABSL_DEPRECATED("AesGcmSivCryptor will be removed in a future release")
^
external/com_google_absl/absl/base/macros.h:149:49: note: expanded from macro 'ABSL_DEPRECATED'
#define ABSL_DEPRECATED(message) __attribute__((deprecated(message)))
```
cc @tiziano88

**Comment by sethmoo** [comment]
Thanks for the heads up. This is indeed a bug, and we'll address it soon.

That said, I'm curious how you're running into this. It appears that ABSL_DEPRECATED is a Clang-only attribute. Do you have code building with Clang that has a dependency on aes_gcm_siv.h?

**Comment by ipetr0v** [comment]
Yes, we are compiling a `dev` version of the Oak server with `clang`:
https://github.com/project-oak/oak/blob/46361f6ec10acc7196dc81765aa65416b5eefb39/scripts/build_server_dev#L23-L29
that currently uses `aes_gcm_siv.h`:
https://github.com/project-oak/oak/blob/46361f6ec10acc7196dc81765aa65416b5eefb39/oak/server/storage/storage_processor.h#L22
