### ISSUE TITLE
SGX with protobuf

### ISSUE THREAD

**Issue by light1021** [google/asylo#6]
Hi, Asylo uses protobuf for trustapplication  enclave input and output, but as far as I know Protobuf can not be used inside an enclave due to some io problem, like iosfwd..  Then how can asylo work with SGX ? Thanks!
Regards 
you.w.l

**Comment by KeithMoyer** [comment]
We are not aware of any issue with using Protocol Buffers inside of Asylo enclaves.  In fact, you can see them in use with our [available examples](https://github.com/google/asylo/tree/master/asylo/examples).  Could you clarify the issues you are having?

**Comment by light1021** [comment]
Hi, Thanks for answering my question. I haven't try those examples in Asylo. I have tried protobuf with original SGX SDK, but it doesn't work. I will try those examples latter. Thanks
Regards
You.W.l

**Comment by KeithMoyer** [comment]
Yes, what Asylo provides is a broad platform, not merely a wrapper around any given backend technology. We currently have support for C++11 and a broad (and ever growing) subset of POSIX, which allows the use of lots of things not typically thought of as being in an enclave.

For future questions about support, I think the [asylo-users](https://groups.google.com/forum/#!forum/asylo-users) list might be an appropriate medium. If you have issues or questions with using the examples or protobufs, feel free to check in there.  For now, I'll close this issue, though.
