### ISSUE TITLE
build error when introduce opencv to enclave

### ISSUE THREAD

**Issue by yc-huang** [google/asylo#60]
I‘m trying to introduce opencv to my enclave application. I started from modifying the hello_world example as following:
1. add some opencv code to hello_enclave.cc:
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
...
cv::Mat image;
image = cv::imread( "image.jpg", 1 );
LOG(INFO) << "Hello " << visitor;

2. add dependence to BUILD:
cc_unsigned_enclave(
    name = "hello_enclave_unsigned.so",
    srcs = ["hello_enclave.cc"],
    deps = [
        ":hello_cc_proto",
        "@com_google_absl//absl/strings",
        "@com_google_asylo//asylo:enclave_runtime",
        "@com_google_asylo//asylo/util:logging",
        "@com_google_asylo//asylo/util:status",
        "@opencv//:opencv"
    ],
)

3. define opencv dependence in WORKSPACE:
new_local_repository(
    name = "opencv",
    path = "/opt/my-project/opencv_bazel/opencv/opencv-install",
    build_file = "opencv.BUILD",
)

4. and here's the opencv.BUILD:
cc_library(
    name = "opencv",
    srcs = glob(["lib/*.so*"]),
    hdrs = glob(["include/**/*.hpp", "include/**/*.h"]),
    includes = ["include"],
    visibility = ["//visibility:public"],
    linkstatic = 1,
)

When I execute bazel run, following error encountered:

bazel run --config=sgx-sim //hello_world:hello_world --verbose_failures
INFO: Analyzed target //hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
INFO: From Signing for debug: //hello_world:hello_enclave_unsigned_sgx_sim.so:
Symbol table incorrect The input enclave file is not correct. Error happened while signing the enclave. <EnclaveConfiguration> <ProdID>0</ProdID> <ISVSVN>0</ISVSVN> <StackMaxSize>0x40000</StackMaxSize> <HeapMaxSize>0x2000000</HeapMaxSize> <TCSNum>12</TCSNum> <TCSPolicy>0</TCSPolicy> <DisableDebug>0</DisableDebug> <ProvisionKey>0</ProvisionKey> <EnableKSS>0</EnableKSS> <MiscSelect>0</MiscSelect> <MiscMask>0xffffffff</MiscMask> </EnclaveConfiguration>
ERROR: /opt/my-project/hello_world/BUILD:56:1: output 'hello_world/hello_enclave_sgx_sim.so' was not created
ERROR: /opt/my-project/hello_world/BUILD:56:1: not all outputs were created or valid
Target //hello_world:hello_world failed to build
INFO: Elapsed time: 0.859s, Critical Path: 0.08s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

Will try to build opencv as static library later, might that helps?

**Comment by yc-huang** [comment]
changed to use opencv static library, still can't build...It looks like that the library is incompatible with the ld command?

bazel run --config=sgx-sim //hello_world:hello_world
INFO: Analyzed target //hello_world:hello_world (1 packages loaded, 270 targets configured).
INFO: Found 1 target...
ERROR: /opt/my-project/hello_world/BUILD:43:1: Linking of rule '//hello_world:hello_enclave_unsigned_sgx_sim.so' failed (Exit 1) x86_64-elf-gcc failed: error executing command external/com_google_asylo_toolchain/toolchain/bin/x86_64-elf-gcc -shared -Wl,-S -o bazel-out/k8-fastbuild/bin/hello_world/libhello_enclave_unsigned_sgx_sim.so ... (remaining 160 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
external/com_google_asylo_toolchain/toolchain/bin/../lib/gcc/x86_64-elf/7.4.0/../../../../x86_64-elf/bin/ld: bazel-out/k8-fastbuild/bin/external/linux_sgx/libtrts_sim.lo(xsave_gnu.pic.o): unrecognized relocation (0x2a) in section `.nipx'
external/com_google_asylo_toolchain/toolchain/bin/../lib/gcc/x86_64-elf/7.4.0/../../../../x86_64-elf/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Target //hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 21.843s, Critical Path: 10.83s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by sethmoo** [comment]
It looks like the problem here is that OpenCV is not being built with the same toolchain as Asylo. This is likely leading to incompatibilities between toolchains.

Instead of using `new_local_repository` to reference a pre-built OpenCV, I'd recommend using `new_git_repository` to download the OpenCV source. You'll need to add a `BUILD.opencv` file to natively build OpenCV with the same toolchain as Asylo. I poked around a little online and found this [ `BUILD.opencv`](https://github.com/hatstand/symmetrical-octo-fiesta/blob/28714db06cfbb4574efa00d395facbb3e53024b6/BUILD.opencv) file that you can reference or reuse. 

I have not tried that solution, but [this](https://stackoverflow.com/a/35024014) discussion on StackOverflow indicates the BUILD file is good.

Cheers,
Seth

**Comment by yc-huang** [comment]
Thanks @sethmoo for your suggestion, I can finally build opencv with bazel, but still can't build the whole project.  I'm invoking cv::imread("image.jpg") but it says undefined reference to: `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'.  Does that means I can't simply calling a 3rd party lib in an enclave application?

-----------------------------------------------------------------------------------
bazel run --config=sgx-sim //hello_world:hello_world -- --names "nick, bob"
DEBUG: Rule 'opencv' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "d7504ecaed716172806d932f91b65e2ef9bc9990", shallow_since = "1481894396 +0300" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'opencv' which is a new_git_repository (rule definition at /root/.cache/bazel/_bazel_root/20c1edcf286ac3c607f1193d498bc30d/external/bazel_tools/tools/build_defs/repo/git.bzl:182:22):
 - /opt/my-project/new/WORKSPACE:30:1
INFO: Analyzed target //hello_world:hello_world (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /opt/my-project/new/hello_world/BUILD:43:1: Linking of rule '//hello_world:hello_enclave_unsigned_sgx_sim.so' failed (Exit 1) x86_64-elf-gcc failed: error executing command external/com_google_asylo_toolchain/toolchain/bin/x86_64-elf-gcc -shared -Wl,-S -o bazel-out/k8-fastbuild/bin/hello_world/libhello_enclave_unsigned_sgx_sim.so ... (remaining 145 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/hello_world/_objs/hello_enclave_unsigned_sgx_sim/hello_enclave.pic.o: In function `HelloApplication::Run(asylo::EnclaveInput const&, asylo::EnclaveOutput*)':
hello_enclave.cc:(.text._ZN16HelloApplication3RunERKN5asylo12EnclaveInputEPNS0_13EnclaveOutputE[HelloApplication::Run(asylo::EnclaveInput const&, asylo::EnclaveOutput*)]+0x123): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
Target //hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 8.032s, Critical Path: 7.62s
INFO: 1 process: 1 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

**Comment by yc-huang** [comment]
Following is build files I used to introduce opencv to the hello_world example as Seth suggested:
1. add those to WORKSPACE:
load("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")
new_git_repository(
    name = "opencv",
    remote = "https://github.com/opencv/opencv",
    build_file = "BUILD.opencv",
    tag = "2.4.13.2",
)

http_archive(
    name = "net_zlib",
    build_file = "@com_google_protobuf//:third_party/zlib.BUILD",
    sha256 = "c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1",
    strip_prefix = "zlib-1.2.11",
    urls = ["https://zlib.net/zlib-1.2.11.tar.gz"],
)


bind(
    name = "zlib",
    actual = "@net_zlib//:zlib",
)

2. external/BUILD.opencv:
cc_library(
    name = "dynamicuda",
    hdrs = glob([
        "modules/dynamicuda/include/**/*.hpp",
    ]),
    includes = [
        "modules/dynamicuda/include"
    ],
)

cc_library(
    name = "opencv_core",
    visibility = ["//visibility:public"],
    srcs = glob(["modules/core/src/**/*.cpp"]),
    hdrs = glob([
        "modules/core/src/**/*.hpp",
        "modules/core/include/**/*.hpp",
        "include/**/*.hpp",
        "build/*.h",
        "build/*.hpp",
        "build/3rdparty/ippicv/ippicv_lnx/icv/include/*.h",
        "build/3rdparty/**/*.h",
        "modules/imgcodecs/src/*.hpp",
        "modules/imgcodecs/include/**/*.hpp",
        "modules/imgcodecs/include/**/**/*.hpp",
        "modules/imgcodecs/include/**/**/*.h",
        "modules/highgui/src/*.hpp",
        "modules/highgui/include/**/*.hpp",
        "modules/highgui/include/**/**/*.hpp",
        "modules/highgui/include/**/**/*.h",
        "modules/core/include/**/**/*.hpp",
        "modules/core/include/**/**/*.h",
        "modules/core/include/**/*.hpp"
     ]) + [
        ":module_includes",
        ":cvconfig",
        ":cv_cpu_config",
        ":opencv_data_config",
        ":custom_hal",
        ":version_string",
    ],
    copts = [
        "-Imodules/dynamicuda/include",
        "-D__OPENCV_BUILD=1",
    ],
    # Note that opencv core requires zlib and pthread to build.
    linkopts = [],
    includes = [
        "modules/core/include",
        "include",
        "modules/imgcodecs/include",
        "modules/highgui/include",
    ],
    deps = [
        ":dynamicuda",
        "//external:zlib",
    ],
)

genrule(
    name = "module_includes",
    cmd = "echo '#define HAVE_OPENCV_CORE' > $@",
    outs = ["opencv2/opencv_modules.hpp"],
)

genrule(
    name = "cvconfig",
    outs = ["cvconfig.h"],
    cmd = """
cat > $@ <<"EOF"
// JPEG-2000
#define HAVE_JASPER

// IJG JPEG
#define HAVE_JPEG

// PNG
#define HAVE_PNG

// TIFF
#define HAVE_TIFF
// Compile for 'real' NVIDIA GPU architectures
#define CUDA_ARCH_BIN ""

// NVIDIA GPU features are used
#define CUDA_ARCH_FEATURES ""

// Compile for 'virtual' NVIDIA PTX architectures
#define CUDA_ARCH_PTX ""
EOF"""
)

genrule(
    name = "custom_hal",
    outs = ["custom_hal.hpp"],
    cmd = """
cat > $@ << "EOF"
#ifndef _CUSTOM_HAL_INCLUDED_
#define _CUSTOM_HAL_INCLUDED_

#endif
EOF"""
)


genrule(
    name = "cv_cpu_config",
    outs = ["cv_cpu_config.h"],
    cmd = """
cat > $@ << "EOF"

#define CV_CPU_COMPILE_SSE 1
#define CV_CPU_BASELINE_COMPILE_SSE 1

#define CV_CPU_COMPILE_SSE2 1
#define CV_CPU_BASELINE_COMPILE_SSE2 1

#define CV_CPU_COMPILE_SSE3 1
#define CV_CPU_BASELINE_COMPILE_SSE3 1
#define CV_CPU_BASELINE_FEATURES 0 \
    , CV_CPU_SSE \
    , CV_CPU_SSE2 \
    , CV_CPU_SSE3 \


// OpenCV supported CPU dispatched features

#define CV_CPU_DISPATCH_COMPILE_SSE4_1 1
#define CV_CPU_DISPATCH_COMPILE_SSE4_2 1
#define CV_CPU_DISPATCH_COMPILE_FP16 1
#define CV_CPU_DISPATCH_COMPILE_AVX 1
#define CV_CPU_DISPATCH_COMPILE_AVX2 1
#define CV_CPU_DISPATCH_COMPILE_AVX512_SKX 1


#define CV_CPU_DISPATCH_FEATURES 0 \
    , CV_CPU_SSE4_1 \
    , CV_CPU_SSE4_2 \
    , CV_CPU_FP16 \
    , CV_CPU_AVX \
    , CV_CPU_AVX2 \
    , CV_CPU_AVX512_SKX \

EOF"""
)

genrule(
    name = "opencv_data_config",
    outs = ["opencv_data_config.hpp"],
    cmd = """
cat > $@ << "EOF"

#define OPENCV_INSTALL_PREFIX "/usr/local"

#define OPENCV_DATA_INSTALL_PATH "share/opencv4"

#define OPENCV_BUILD_DIR "/opt/my-project/new/opencv-4.3.0/build"
#define OPENCV_DATA_BUILD_DIR_SEARCH_PATHS \
    "..//"

#define OPENCV_INSTALL_DATA_DIR_RELATIVE "../share/opencv4"

EOF"""
)

genrule(
    name = "version_string",
    outs = ["version_string.inc"],
    cmd = """
cat > $@ <<"EOF"
"\\n"
EOF"""
)

**Comment by sethmoo** [comment]
It looks like you're not building the image codecs. I don't know OpenCV myself, but I looked on the github repo and cv::imread seems to be defined in [modules/imgcodecs/src/loadsave.cpp](https://github.com/opencv/opencv/blob/8d78400052c9e6b60374364163f234790251b8fb/modules/imgcodecs/src/loadsave.cpp#L622)

However, your build rule is only building modules/core:
```
cc_library(
    name = "opencv_core",
    visibility = ["//visibility:public"],
    srcs = glob(["modules/core/src//*.cpp"]),
    hdrs = glob([...
```

You'll need to include the sources for the modules you need for your project. It might be as simple as including `modules/imgcodes//*.cpp` in the srcs.

OpenCV is not something Asylo supports directly, so you're a little bit on your own getting the bazel rules correct for all the OpenCV modules you need for your project.

Regards,
Seth

**Comment by yc-huang** [comment]
Sorry my fault; I made a mistake to think that Asylo build system might change the shape of the functions that I called inside the enclave app...
