### ISSUE TITLE
Mitigation for Iago attack

### ISSUE THREAD

**Issue by Gavincrz** [google/asylo#67]
Dear Asylo Developers,

I found a potential lack of mitigation issue in some functions. enc_untrusted_readlink() function returns the untrusted number of bytes read to the Asylo application without verification. 

It is not a vulnerability unless the application running inside Asylo uses the readlink()'s return value unsafely. 

Many legacy applications assume the readlink()’s return value is less than or equal to the max buffer length it provided. For example, the following code snippet is common in legacy applications:

```
char buf[MAX_LEN];
ssize_t ret = readlink(path, buf, MAX_LEN);
buf[ret] = '\0';
```

In Asylo's threat model, the readlink()'s return value provided by the OS is untrusted. If a developer writes a similar code when using Asylo, the malicious OS could set one byte outside the buffer to zero by providing a return value greater than MAX_LEN and cause an Iago attack

Our research found that some legacy code also use the write() related syscall's return value to do pointer arithmetic. (write()'s return value also should be less than or equal to the input length)

I notice that you added some mitigation for enc_untrusted_read():

```
if (ret != -1 && ret > count) {
	 ::asylo::primitives::TrustedPrimitives::BestEffortAbort(
	 "enc_untrusted_read: read result exceeds requested");
}
```

I think it would be beneficial to apply the same mitigation to enc_untrusted_readlink(), enc_untrusted_write(), enc_untrusted_pread64() and enc_untrusted_pwrite64().

Best,
Rongzhen(Gavin) Cui

**Comment by kongoshuu** [comment]
Hi Rongzhen,

Thank you for reaching out. Checking the return value from the untrusted side in those syscalls would help to provide better security for user cases as you mentioned. We added the check to those calls. Thanks for helping improve Asylo!

Regards,
Chong
