### ISSUE TITLE
hello-world symbol problem

### ISSUE THREAD

**Issue by py-ae** [google/asylo#7]
Hello Asylo Team,
I am trying to run the hello-world example manually without Docker and the build keeps failing with the following error:
```
$ bazel run --config=enc-sim //hello_world -- --names="${NAMES}"
INFO: Analysed target //hello_world:hello_world (59 packages loaded).
INFO: Found 1 target...
INFO: From ProtoCompile external/com_google_protobuf/python/google/protobuf/any_pb2.py [for host]:
external/com_google_protobuf/python: warning: directory does not exist.
ERROR: /home/philip/asylo/sdk/asylo/examples/hello_world/BUILD:40:1: Linking of rule '//hello_world:hello_enclave_unsigned.so' failed (Exit 1)
external/com_google_asylo_sgx_backend/toolchain/bin/../lib/gcc/x86_64-elf/7.3.0/../../../../x86_64-elf/bin/ld: bazel-out/k8-fastbuild/bin/external/linux_sgx/libcrypto_px.a(pcpaesauthgcmca.pic.o): relocation R_X86_64_PC32 against symbol `ippsAES_GCMReset' can not be used when making a shared object; recompile with -fPIC
external/com_google_asylo_sgx_backend/toolchain/bin/../lib/gcc/x86_64-elf/7.3.0/../../../../x86_64-elf/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Target //hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 348.496s, Critical Path: 14.00s
INFO: 752 processes: 752 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
I've tried running with the '--copt="-fpic"' and '--force_pic' arguments but have had no luck.
Any tips? Thank you!

**Comment by KeithMoyer** [comment]
Thank you for your report.

We actually just started seeing this a couple of hours ago as well.  I have traced it back to an upgrade to Bazel 0.15.0; downgrading to Bazel 0.14.0 has resolved the issue for us (note: the Asylo build container image is still using Bazel 0.14.0 and is unaffected, but I know you are not using that).

Can you try that as a workaround?  I will continue to see what has changed in 0.15.0 and what needs to change to support that newer version.

**Comment by KeithMoyer** [comment]
The changes in 2975aea2ce0f9fac97ecbe839185f031ca36260b should add the needed changes to use Bazel 0.15.0.  They somewhat refactored how linker flags are passed through crosstools, and there was just some more instructions needed in the CROSSTOOL file in order to continue passing in the linkopts flags as they were before.
