### ISSUE TITLE
Query: GDB and debugging

### ISSUE THREAD

**Issue by py-ae** [google/asylo#9]
Hello Asylo team,

I've been trying step through the hello_world example (manual installation not Docker container) with GDB but am unable to properly read symbols.  More specifically, I'm trying GDB on the hello_world_host_loader but getting "no debugging symbols found".
I have tried building the example with the Bazel options --strip=never and --compilation_mode=dbg but have had no luck.
Do you have any tips?

Thanks!

**Comment by deeglaze** [comment]
Yes, Keith has recently addressed this same question on the asylo-users Google Group https://groups.google.com/d/msg/asylo-users/OMVJW6hOgiM/PlDsdX1kDgAJ

Please reopen with comments if this does not solve your issue :)
